# Generated by Django 3.1.7 on 2021-03-02 20:33

from django.db import migrations, models
import store.models.utils.uploads


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210302_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to=store.models.utils.uploads.uploadBookMedia),
        ),
    ]
