// Order
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';

// Filter
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const GET_BOOKS_BY_FILTER = 'GET_BOOKS_BY_FILTER';